name: ubuntu install

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    strategy:
      matrix:
        BUILD_TYPE: [Release]
        CXX: [g++-14]
        SHARED: [On, Off]

    steps:
    - uses: actions/checkout@v4

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: install
      run: |
        cmake --preset=github-workflow-vcpkg \
          -DCMAKE_CXX_COMPILER=${{matrix.CXX}} \
          -B build-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}} \
          -S ${{github.workspace}} \
          -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
          -DCMAKE_INSTALL_PREFIX=/tmp/install-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}} \
          -DBUILD_SHARED_LIBS=${{matrix.SHARED}}
        cmake --build build-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}} --target install
        rm -rf build-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}}

    - name: build and use example
      run: |
        cmake \
          -DCMAKE_CXX_COMPILER=${{matrix.CXX}} \
          -B build-example-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}} \
          -S ${{github.workspace}}/examples/use_with_findpackage \
          -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
          -DCMAKE_INSTALL_PREFIX=/tmp/install-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}}
        cmake --build build-example-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}}
        build-example-${{matrix.BUILD_TYPE}}-${{matrix.SHARED}}/executable
