name: ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
        CXX: [g++-12, g++-13, g++-14, clang++-16, clang++-17, clang++-18]

    steps:
    - uses: actions/checkout@v4

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Configure CMake
      run: cmake --preset=github-workflow-vcpkg -DCMAKE_CXX_COMPILER=${{matrix.CXX}} -B ${{github.workspace}}/build-${{matrix.BUILD_TYPE}} -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build-${{matrix.BUILD_TYPE}} --config ${{matrix.BUILD_TYPE}}

    - name: Unit test
      working-directory: ${{github.workspace}}/build-${{matrix.BUILD_TYPE}}
      run: ctest -C ${{matrix.BUILD_TYPE}}

    - name: Tool test "lemacsum"
      working-directory: ${{github.workspace}}
      run: test/test_tool.sh ${{github.workspace}}/build-${{matrix.BUILD_TYPE}}/lemacsum
